spring.application.name=MotoWrapBackend

#h2
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.h2.console.enabled=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://db.delarkdqmohemjojksez.supabase.co:5432/postgres?sslmode=require
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Sayan_hello_mondal@3338


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.data-source-properties.sslmode=require

#security
spring.security.user.name=sayan
spring.security.user.password=2003


# JWT
jwt.secret=9b169774b57a098d7b3dd032f957921117fc0d923847c2471e233d517168ab50c051a99661bb371af61a05e7a8108afe16341fc0425169496d601dff97c46e6d
jwt.expiration=86400000