spring.application.name=MotoWrapBackend

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.expiration=2592000000

spring.jackson.serialization.write-dates-as-timestamps=false