spring.datasource.url=jdbc:postgresql://db.delarkdqmohemjojksez.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Sayan_hello_mondal@3338
spring.datasource.driverClassName=org.postgresql.Driver

jwt.secret=9b169774b57a098d7b3dd032f957921117fc0d923847c2471e233d517168ab50c051a99661bb371af61a05e7a8108afe16341fc0425169496d601dff97c46e6d

spring.security.user.name=sayan
spring.security.user.password=2003

# optional: show SQL in dev
spring.jpa.show-sql=true